apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata
  namespace: mmenke
  labels:
    app: esdata
    tier: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
