apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-frontend-cicd
  namespace: datexis
  labels:
    app: trainer-frontend-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer-frontend-cicd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trainer-frontend-cicd
    spec:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /tmp/trainer-frontend-cicd"]
          volumeMounts:
          - name: work
            mountPath: "/tmp/trainer-frontend-cicd"
      containers:
      - name: github-runner
        image: tcardonne/github-runner
        securityContext:
          privileged: true
        env:
        - name: RUNNER_NAME
          value: "trainer-frontend-cicd"
        - name: RUNNER_TOKEN
          value: "AAJ7Q64TQ5NXUUQURYCPG7K7G7ARW"
        - name: RUNNER_REPOSITORY_URL
          value: "https://github.com/DATEXIS/TraiNER-Frontend"
        - name: RUNNER_WORK_DIRECTORY
          value: "/tmp/trainer-frontend-cicd"
        volumeMounts:
        - name: work
          mountPath: "/tmp/trainer-frontend-cicd"
        - name: dockersock
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: work
        hostPath:
          path: "/tmp/trainer-frontend-cicd"
      - name: dockersock
        hostPath:
          path: "/var/run/docker.sock"
