version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - .:/code
    links:
      - postgres:postgres


  data:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgrsql/data
      - model-data:/var/lib/TraiNER/models
    command: "true"

  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgrsql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      #POSTGRES_USER: "postgres"


volumes:
  db-data:
  model-data:
